### ISSUE TITLE
SOLiD sequencing data processing

### ISSUE THREAD

**Issue by dahun73** [FelixKrueger/TrimGalore#118]
Hello :)

I'm trying to handle SOLiD sequencing data. But I have one question. In recent version of TrimGalore, it does not support SOLiD sequencing data. So I just want to trim adapter sequences. In this case, Does TrimGalore support standard SOLiD adapter sequences? If not, should I put in the specific adapter sequences.

Thank you 
Dahun

**Comment by FelixKrueger** [comment]
Hi Dahun,

I don't think I heard the term SOLiD since 2012 or so :). I am afraid Trim Galore does not support SOLiD trimming, and we have no plans to add support for it. You can however use Cutadapt for it, please see here: https://cutadapt.readthedocs.io/en/v1.15/colorspace.html#colorspace-reads. Good luck!

**Comment by dahun73** [comment]
Thank you so much for your help :)

Have a good day!!
