### ISSUE TITLE
Run TrimGalore on a FASTA input

### ISSUE THREAD

**Issue by vkkodali** [FelixKrueger/TrimGalore#139]
Is there a way to run TrimGalore on FASTA input files? I am only in interested in automatic detection of the adapters and trimming them without quality trimming.

**Comment by FelixKrueger** [comment]
Trim Galore doesn't explicitely handle FastA format, but there is a chance that it will work nevertheless as I think Cutadapt (which does the trimming itself) should auto-detect the file format. Otherwise there are numerous options online to convert FastA to FastQ very quickly.

If you don't want to perform quality trimming you can just set  `-q 0`, which should only trim adapter sequences. I hope this helps.
