### ISSUE TITLE
trimmed and val

### ISSUE THREAD

**Issue by DWY1a** [FelixKrueger/TrimGalore#160]
When I used trimgalore, the file sample_1_trimmed.fq.gz was generated, then sample_1_val.fq.gz was generated, and the trimmed file was removed. I generated a full trimmed.fq.gz file during the run, but did not generate a full val.fq.gz, so how do I do this? Can I just start running again?

**Comment by FelixKrueger** [comment]
Hi there, I am not exactly sure I understand what the problem is but just generally:
- single-end trimming gives rise to files ending in `trimmed.fq.gz`
- paired-end trimming (`--paired`) gives rise to the `trimmed.fq.gz` intermediate files, and validated paired-end trimmed files engint in `val_R[12].fq.gz`

You can of course re-issee the trimming process from untrimmed `fastq.gz` files, the newly generated trimmed files and trimming reports will overwrite already existing files.
