### ISSUE TITLE
Trim just one read in paired-end data by TrimGalore

### ISSUE THREAD

**Issue by iranianuser** [FelixKrueger/TrimGalore#193]
Hello,
I m using TrimGalore to trim my BS-seq paired-end data, but there is an adapter just in one read (read 1). Can I trim just one read in paired-end reads and run bismark for alignment next? Is there any problem because the read lengths make different after trimming? 
I use this:
trim_galore --stringency 3 SRR2988823_1.fastq
Is it necessary to use --paired option? 

Thank you

**Comment by FelixKrueger** [comment]
Hmm, that's an interesting question (not sure it has ever come up so far).

Generally, you cannot trim just a single file because that has the potential to interrupt the sync between R1 and R2 that is required for downstream steps such as alignments. So yes, you will need to use `--paired`

```
trim_galore --paired SRR2988823_1.fastq SRR2988823_2.fastq
```

By default, Trim Galore looks for the same adapter for both reads, do if Read 2 doesn't contain this adapter (why do you suspect that R1 will be affected but not R2?) then it simply won't get trimmed. You could also select the option `-a2 ` and give it a sequence that doesn't occur in the read, but there is no option not to trim at all currently.

**Comment by iranianuser** [comment]
Dear Felix,
Thanks for your quick response
well I did nt see any adapter sequence in "overrepresented sequence" icon in R2.
I ll try your suggestions and tell you next

**Comment by FelixKrueger** [comment]
Ah ok that makes more sense. As a general rule, the read-through adapter sequence you expect for sequencing runs doesn't show up as Overrepresented Sequence because of several reasons: that module looks for sequences that are perfectly identical, starts at base 1, and only looks at the first 50bp. Adapter contamination on the other hand is at the 3 end, starts at variable positions (depending on the fragment length/insert size), and thus tends to show up in the Adapter Contamination module.

If in doubt, just run Trim Galore in its default mode (as shown above), it should do just the right thing. Good luck!
