### ISSUE TITLE
Add option to hard-trim reads to a certain read length without any adapter/quality trimming

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/TrimGalore#30]
I am finding myself wanting to hard-trim reads to a certain length from the 5' end fairly often, and it should be straight forward to add a new option e.g. `--hardtrim <INT>` to accomplish this.

**Comment by FelixKrueger** [comment]
Added option `--hardtrim5 INT` to enable hard-clipping from the 5' end. This option processes one or more files (plain FastQ or gzip compressed files) and produce hard-trimmed FastQ files ending in 
`.{INT}bp.fq(.gz)`. This will make it so much easier to explore some data or find out what went wrong...

**Comment by ethering** [comment]
I'm confused as to what --hardtrim5 INT is supposed to do.
From the docs:
"Instead of performing adapter-/quality trimming, this option will simply hard-trim sequences to bp from the 5'-end." and "The option --hardtrim5 INT allows you to simply hard-clip sequences from their 5' end. This option processes one or more files (plain FastQ or gzip compressed files) and produces hard-trimmed FastQ files ending in .{INT}bp.fq(.gz). We found this quite useful in a number of scenarios where we wanted to removed biased residues from the start of sequences."

From this, I expected if you had fastq reads of length 100 and you used the command:
trim_galore --hardtrim5 10 input_R1.fastq

I would be left with bases that would have previously been at position 11-100.
But, it outputs bases 1-10. Is that what this option is supposed to do, or is this a bug?

**Comment by FelixKrueger** [comment]
Hi Graham, 

On reading my comment (and the help info) again I have to say that I would probably also interpret it the way you read it. 

Instead of saying `hard-trim sequences to X bp from the 5'-end` it should rather read `from the 3'-end`.
So a sequence with `--hardtrim5 10` should be trimmed like so:
 
`CGGTGTTTTCGAATTAGAAAAATATGTATAGAGGAAATAGATATAAAGGCGTATTCGTTATTG`
`CGGTGTTTTC`

Sorry for the confusion, I will definitely update the documentation tomorrow.

**Comment by FelixKrueger** [comment]
I have now added a new option `--hardtrim3 INT` to trim sequences from their 5' end (and leave only sequences at the 3'-end). I have also tried to update the help text and added examples to the documentation (https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md#step-4-specialised-trimming) to correct the confusing text. Hope it is now clearer and works as intended.
