### ISSUE TITLE
Path of Python executable via cutadapt

### ISSUE THREAD

**Issue by ptrebert** [FelixKrueger/TrimGalore#53]
Hi,

I am running in an issue with trim_galore version `0.6.0_dev` by the way it wants to find the location of the Python executable. When trim_galore reads the first line of cutadapt (around line number 2178), this is in my case (cutadapt v2.0) the following:

```bash
#!/bin/sh
'''exec' /long/path/to/conda/envs/deepsv/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
[omitted rest of cutadapt file]
```
Though I am not a Perl programmer, I think I can see that this is not handled by trim_galore

Best,
Peter

**Comment by FelixKrueger** [comment]
Hi Peter,

Thanks for reporting this; when I look at the first line of Cutadapt over here it says: `#!/bi/apps/python/3.5.1/bin/python3`, for which it works well. I could see three ways of action we could take:
1) You could edit the path in Trim Galore manually (but that seems a little tedious)
2) I could add a second case distinction to deal with your case; it could look for  `#!/bin/sh` in line 1, and if found read line 2 and try to figure out the version there (by the way, is this Pyhton (2) you are using?
3) Or finally, I could add an option `--path_to_python /path/to/python[2/3]`, and you would have to make sure that this is what Cutadapt is using. 

Do you have a preferred option?

**Comment by ptrebert** [comment]
Hi Felix,
thanks for the quick reply. Well, I can live with any of those (first one is of course bound to break soon-ish). However, wouldn't it be more elegant to query the shell for the path of Python, or just assume that it is in the PATH and fail if it isn't? Since I installed cutadapt in a fresh Conda environment from the bioconda channel, I would assume the way the cutadapt script looks like in my environment is pretty common/generic.
To answer your in-between question: it's Python 3.6
Thanks for your support.
Best,
Peter

**Comment by FelixKrueger** [comment]
I'll try to address this tomorrow, thanks for the info.

**Comment by FelixKrueger** [comment]
Hi Peter,

This has taken somewhat longer than I had hoped... 

We don't really want to just do a `which python` query on the shell to find the version of Python, as this is quite likely to likely to break because:
- the Python version in the PATH is not necessarily the same as e.g. in a Conda environment
- or in our case, `python` and `python3` give you different results for this, and only the shebang line of Cutadapt tells you which version it will be using (and of course Cutadapt breaks if you use it with the wrong version of Python...)

To understand the issue a bit better, I fired up a virtual machine running CentOS 7, and installed Anaconda first, and then installed Trim Galore via:

```
conda install -c bioconda trim-galore 
conda install -c bioconda/label/cf201901 trim-galore 
```

Apart from the fact that this pulled down version 0.5.0 of Trim Galore, and 1.1.8 Cutadapt, the first line of Cutadapt is indeed a `#!/../python` shebang.

I then removed Anaconda, and installed Miniconda instead, and there I got a very similar looking start of Cutadapt:

```
#!/bin/sh
'''exec' /long/path/to/conda/envs/deepsv/bin/python "$0" "$@"
' '''
```

This means that the person maintaining Cutadapt for Miniconda changed the Python Shebang to now be a `bash` script instead... So technically, this is really an issue that needs to be addressed in the Conda environment rather than Trim Galore itself. 

I have nevertheless tried to change it now, so that it first attempts to determine the version of Python used in the way it was. If that fails, e.g. because the first line in Cutadapt had been modified, the version of Python is set to 'could not detect', and we simply let Cutadapt itself deal with the problem of resolving the environment problem introduced by Miniconda. I haven't done extensive testing on this, but if Trim Galore had been installed with Miniconda and you would use a command such as:

`trim_galore -j 2 input_file.fastq`

- with Python3: Cutadapt would run just fine (using 2 cores)
- with Python2.7: Cutadapt would die with something like this: `ERROR: multi-core processing not supported with Python 2`

Could you please clone the latest dev version of Trim Galore and let me know if it now works in your hands? Addressed in 19f00cf05d60f2c020d4b9d28054f0793527fd9b.

Cheers, Felix

**Comment by ptrebert** [comment]
Hi Felix,
well, this sounds a lot messier under the hood than I had expected - thanks for taking care of this. I have good news and bad news: good news is, yes, seems like the path resolution now works also when running in a 'miniconda' environment. Bad news is that there appears to be also a bug in cutadapt, so I can't test your fix from start to end.

One remark/question: in the log output, I see the entry `Trimming mode: paired-end` and afterwards the log message `Processing reads on 2 cores in single-end mode ...`
I assume the first one is coming from trim_galore and the second one is generated by cutadapt, which causes this discrepancy?

Best,
Peter

**Comment by FelixKrueger** [comment]
Replying to your second remark first: Yes, the Trimming mode: paired-end is from Trim Galore, because under the hood (and for historical reasons) it runs Cutadapt twice in single-end mode, and then executes the 'validation' step on the two single-end trimmed files that deals with the extra parameters for paired-end mode.

Hmm, so is there anything I can assist you with in getting things to run? Ideally, the miniconda maintainers would update both Trim Galore and Cutadapt to the latest version, and make this work somehow...

**Comment by ptrebert** [comment]
I think I'll close this for now; your fix seems to work, and I need to sort out the situation with cutadapt first - if this leads me back here, you'll notice :-)
Thanks again!

**Comment by FelixKrueger** [comment]
Thanks, and good luck! Felix

**Comment by ptrebert** [comment]
Just to confirm: `trim_galore v0.6.1_dev` together with `cutadapt v2.1` works as expected.
Thanks.

**Comment by shawpa** [comment]
I am getting the same error as the original poster. However, the program seems to progress just fine. Should I be concerned that this message is showing up?

"Could not detect version of Python used by Cutadapt from the first line of Cutadapt (but found this: >>>#!/bin/sh<<<)
Letting the (modified) Cutadapt deal with the Python version instead"

I am using trim-galore version 0.6.5, cutadapt 2.6, python 3.7.5

Annie

**Comment by FelixKrueger** [comment]
Hi Annie,

If it proceeds fine then I would assume it is all working. As long as you get sensible `...trimming_report.txt` files at the end, it should be all OK.
