### ISSUE TITLE
Is bisulfite data after PolyA trimming incompatible with Bismark ?

### ISSUE THREAD

**Issue by hd4git** [FelixKrueger/TrimGalore#71]
Hi, 

One of the mates of my PE bisulfite data has over representation of PolyA in the reads. 
I know "--polyA" option of trim galore is in experimental stage but I used it anyways after the regular trimming. 
`trim_galore --paired --fastqc --polyA -j 4 sample1_1.fq.gz sample1_2.fq.gz
`
The output files looked better so I used them for alignment with Bismark. But it was surprising to see close to 0% mapping efficiency, so I tried alignment in single end mode. 
That gave nearly 80% mapping efficiency for both the mates when aligned separately. 
So, I tried mapping the files without polyA trimming from the first round of trim galore filtering step.
This went well and I got close to 65% mapping efficiency in paired end mode. 

It seems to me that since the fastq headers get changed after polyA trimming, bismark doesn't seem to be able to recognize the 2 mate pairs. Can you please let me know if there's some way to use PolyA trimmed data with bismark or some other way of trimming polyA. Or should I just use the files as such without polyA trimming, hoping that anyways those reads won't map ??

Thanks !!

**Comment by FelixKrueger** [comment]
Hi @hd4git 

The option `--polyA` is really specifically designed for an RNA kit that specifically produces reads from polyA labelled transcripts (Thermo Fisher, Collibri) https://www.thermofisher.com/uk/en/home/life-science/sequencing/next-generation-sequencing/ngs-library-preparation-illumina-systems/collibri-stranded-rna-library-prep-kits.html?gclid=EAIaIQobChMIv7mB-tXn5QIVibHtCh3dTg7gEAAYASAAEgI7KPD_BwE&ef_id=EAIaIQobChMIv7mB-tXn5QIVibHtCh3dTg7gEAAYASAAEgI7KPD_BwE:G:s&s_kwcid=AL!3652!3!303512728519!p!!g!!collibri.

I haven't specifically tried it for bisulfite data, but I wouldn't be surprised if it did the wrong thing.

If you really insist on trimming a second time, you should probably entertain the idea of using -a {A}10 or so instead of using the option `--polyA`. I am not sure though if I would to that, because these 'problems' tend to sort themselves out at the mapping stage anyway. Why don't you just go ahead and use the default trimming, and see where it takes you?

**Comment by hd4git** [comment]
Hi Felix, 

Thanks for the quick reply. 
I tried mapping the following:
 - default trimming, without polyA trimming, Paired End mode : ~65% mapping efficiency
 - with polyA trimming, single end mode: ~80% mapping efficiency

As I got around 80% mapping efficiency in the second case, I thought I might lose some information if I don't do polyA trimming. So, I was looking for ways to do that and compare the results before moving further. I will try to use -a {A}10 option as you said or cutadapt polyA trimming method. If that doesn't change much then I will proceed with default trimming.

Thanks again !!
