### ISSUE TITLE
Partial matching in adaptor removal (?)

### ISSUE THREAD

**Issue by Ni-Ar** [FelixKrueger/TrimGalore#73]
Hi Felix,

I have an issue with Adaptor trimming the and I'm not really sure if Trim Galore can sort out this scenario. 
I have a sample with many TruSeq Adapter, Index 18 sequences.
I trim them off with using:
```
trim_galore <file.fastq>
              --quality 28 
              --phred33 
              --illumina 
              --length 25 
```
When checking the `fastqc` reports before and after the trimming I notice that:

This sequence:
`GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGG`
is removed by `Trim Galore!`, however this sequence:
`TATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGG`
 is not removed.
The 2 sequences are identical except for the first base (`T` instead of `G`).

How should I set up `trim_galore` to properly remove the second adaptor?
By reading your manual I'm not sure `-s`  or `-e` flags could solve this issue?

Many thanks!

```
trim_galore --version

                          Quality-/Adapter-/RRBS-Trimming
                               (powered by Cutadapt)
                                  version 0.4.1

                             Last update: 20 07 2015
```

**Comment by FelixKrueger** [comment]
Hi @Ni-Ar 

Thanks for your message. First of all, I think it is time to upgrade Trim Galore, your version is already 4.5 years out of date!

I believe your issue can be fairly easily explained, and/or sorted out: 

- The default Illumina adapter sequence is `AGATCGGAAGAGC`, and the allowed error rate is 0.1. That means that it tries to find this sequence, and allows 1 mismatch for the its recognition (0.1 * 13bp = 1 (rounded down)).

- Your first sequence has a perfect 12bp match at the start **GATCGGAAGAGC**ACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGG, albeit the very first `A` of the adapter sequence is missing. This missing is probably regarded as the 1 tolerated error.

- Your second sequence is lacking the initial `A`, and has a mismatch at position 2, which means the sequence has a total of 2 mismatching bases. As a result, the sequence does not get trimmed. I have included a few test scenarios for you to look at further down.

**Possible Actions:**
I think there are two potential considerations here:

1. The scenario you are describing here is a little theoretical, since your sequence 1 or sequence 2 are not what is known as _read-through adapter contamination_, but they are simply left-over primer sequences that are lacking the leading `A` (from A-tailing), and they are not intended to get found and removed. Neither of these sequences would align to a genome anyway, so one could argue that full-length primer sequences do not need to get trimmed as the alignment step will take care of this.

2. If you have a particular reason for still removing these sequences you could allow a higher error rate for the trimming, e.g. `-e 0.2`, which would then remove both your sequences. This comes at the 'cost'; however that you are probably going to 'over-trim' quite a few other sequences as well (I would imagine that 13bp with 2 mismatches do have quite a few genomic (=legiy) locations aleady, which would then be clipped.

I hope that this made sense!? All the best, Felix

```
@test1_A_missing
GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGG
+
AAAAA#EEAEEEEEEEEEEEEEEEEEEEE#EEEEEEEEEEEEEEEAEEEEEEAEEEEEEEEEEEEAEEEEEAEEE
@test2_A_missing_T_mismatch
TATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGG
+
AAAAA#EEAEEEEEEEEEEEEEEEEEEEE#EEEEEEEEEEEEEEEAEEEEEEAEEEEEEEEEEEEAEEEEEAEEE
@test3_full_adapter
AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGG
+
AAAAAA#EEAEEEEEEEEEEEEEEEEEEEE#EEEEEEEEEEEEEEEAEEEEEEAEEEEEEEEEEEEAEEEEEAEEE
@test4_normal_adapter_contamination
TTTTTTTTAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGG
+
AAAAAAAAAAAAAA#EEAEEEEEEEEEEEEEEEEEEEE#EEEEEEEEEEEEEEEAEEEEEEAEEEEEEEEEEEEAEEEEEAEEE
@test3_adapter_contamination_A_missing
TTTTTTTTGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGG
+
AAAAAAAAAAAAA#EEAEEEEEEEEEEEEEEEEEEEE#EEEEEEEEEEEEEEEAEEEEEEAEEEEEEEEEEEEAEEEEEAEEE
@test3_adapter_contamination_A_missing_T_mismatch
TTTTTTTTTATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGG
+
AAAAAAAAAAAAA#EEAEEEEEEEEEEEEEEEEEEEE#EEEEEEEEEEEEEEEAEEEEEEAEEEEEEEEEEEEAEEEEEAEEE
```

**After trimming:**
```
@test1_A_missing

+

@test2_A_missing_T_mismatch
TATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGG
+
AAAAA#EEAEEEEEEEEEEEEEEEEEEEE#EEEEEEEEEEEEEEEAEEEEEEAEEEEEEEEEEEEAEEEEEAEEE
@test3_full_adapter

+

@test4_normal_adapter_contamination
TTTTTTTT
+
AAAAAAAA
@test3_adapter_contamination_A_missing
TTTTTTT
+
AAAAAAA
@test3_adapter_contamination_A_missing_T_mismatch
TTTTTTTTTATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGG
+
AAAAAAAAAAAAA#EEAEEEEEEEEEEEEEEEEEEEE#EEEEEEEEEEEEEEEAEEEEEEAEEEEEEEEEEEEAEEEEEAEEE
```

**Comment by Ni-Ar** [comment]
Hi Felix,

thanks a lot for the detailed explanation! 

I agree with your solution number 1. I basically did not worry and followed up with the alignment.
I believe however there could be also a 3. option. One could run `trim_galore` a second time on the trimmed reads with this parameter.
```
trim_galore --adapter TATCGGAAGAGCACACGTCT
```
It would basically avoid over-trimming and remove from the `fastq` all the reads that are not biologically useful. In my case I don't think I need to do it since it's a small percentage of the reads. It could be relevant, maybe, if these primer/adaptor contaminations would really constitute the majority of the sequencing reads still after trimming, making the `fastq` file smaller and saving time on the alignment. (Maybe). Anyway a very corner case.

Regarding the version, I'll mention it to the person managing the software on my local cluster.
(_Time to start using conda_)

Cheers

**Comment by FelixKrueger** [comment]
That would of course also be an option, but yea it might be a little over the top. I'm glad you are happy to move ahead now!
