### ISSUE TITLE
 How to add custom adaptors in Trim Galore?

### ISSUE THREAD

**Issue by Shicheng-Guo** [FelixKrueger/TrimGalore#76]
Hi Felix, 

I am thinking can we add custom adaptors in TrimGalore. I found there are still some adaptors are remained after trim galore trimming. 

We can add a custom adaptor files so that trim galore can remove all of these adaptors. 

Thanks. 

Shicheng

**Comment by FelixKrueger** [comment]
Hi Shicheng,

I am not generally a big fan of allowing a file with custom adapter sequences, because this is not normally whay you should be wanting to remove.

Trim Galore is designed to remove read-through adapter contamination on the 3' end of reads which can be considered a contamination that prevents reads from aligning. As there can be dozens of different adapters that only differ by a their index sequence, Trim Galore only uses the first 13 or so base pairs that are in common for all index adapters, and are also shared between the Read 1 and Read 2 adapter.

Anything that is left in the sequence file afterwards is not adapter contamination, or at least not one we care (much) about. If you have, for instance, adapter dimers in your library that start with `GATC...` right from base 1, the sequence might look like adapter (and it is the adapter sequence, but it lacks the A at the start (from A-tailing) which is why it doesn't get removed in the first place), but it doesn't contaminate a genuine sequence but is _just_ a contaminating sequence. For any downstream application involving alignments those sequences simply do not align to any genome, and can thus be disregarded.

What did you have in mind, or could you give me an example (e.g. FastQC report) of is left over after trimming (and please provide the command line you used).

Cheers, Felix

**Comment by Shicheng-Guo** [comment]
Hi Felix, 

Great. Thanks for the explanation. It is quite helpful. 

Best, 

Shicheng
