### ISSUE TITLE
Steps in Trim galore

### ISSUE THREAD

**Issue by Hedi65** [FelixKrueger/TrimGalore#79]
Hi Felix 

im wondering steps and order of options are important in Trim galore or not. for instance is it ok to put all options such as --illumina --rrbs --quality --three_prime_clip_R1 --clip_R2 in one command line or we need to do it separately?  I am asking because in trim galore user guide, steps have been clearly defined. 

thanks alot

**Comment by FelixKrueger** [comment]
The order of the options on the command line does not affect the way in which the different steps are carried out. In your example, the order would be:

- set the global option `--rrbs`
- set a quality cut-off
- set the adapter sequence to Illuma, i.e. skipt the adapter-autodetection
- do the quality trimming, then adapter trimming
- finally, apply the 5' and 3' clipping.

Cheers, Felix

**Comment by Hedi65** [comment]
thank you Felix, you mean to apply the 5' and 3' clipping on the output of Trim galore separately (validated files)? 

Best

**Comment by FelixKrueger** [comment]
The 5' and 3'-end clipping is performed after the quality/adapter trimming, but before the validation length check is carried out. So if a sequence would get too short because of the clipping, the sequence/sequence pair is getting removed.

But this all happens automatically, you don't need to think about it separately.

**Comment by Hedi65** [comment]
thanks alot
