### ISSUE TITLE
failed per base sequence content & kmer content.

### ISSUE THREAD

**Issue by sjfleck** [FelixKrueger/TrimGalore#81]
Thank you for your program! 

I'm coming across 2 issues. I have four species that have reads with a length of 251 and one species that has reads with a length of 151. I'm finding strange per base sequence content at the final position (251 and 151) of my trimmed reads for every species and I think it's why I'm failing this parameter in fastqc. I should also mention that I'm also experimenting by trimming the same reads with Trimmomatic and this issue is not happening with that program. 

![PBSC_failure](https://user-images.githubusercontent.com/53409202/74801792-dd0e3a00-52a5-11ea-861a-a423661f0dba.jpeg)

My second issue is that for my single species with reads of length 151, the kmer content fails and I have a bunch of peaks right in the beginning. I'm not exactly sure what this means for my reads. Any insight would be helpful. Thank you for your time
-Steve

![kmc_failure](https://user-images.githubusercontent.com/53409202/74801810-e7303880-52a5-11ea-8ef0-97ba8eb9d747.jpeg)

**Comment by FelixKrueger** [comment]
Hi Steve,

The first issue you described is purely caused by the adapter trimming process itself, and more specifically because Trim Galore uses very strict settings by default (`--stringency 1`). 

**In short**: The Illumina adapter sequence starts with the bases `AGATC...`, and since a single bp at the very end of sequence at the very end of your read could either be a genomic `A` or the first bp of the adapter read through contamination, it is removed. Similarly, if a read ends with `AG`, it is removed, and so on. (One should probably mention that trimming from the 3'-end of reads only occurs when no full match of the adapter sequence was found within the read). I have tried to show this more graphically in slide 28 of the following presentation: https://www.bioinformatics.babraham.ac.uk/training/Methylation_Course/BS-Seq%20theory%20and%20QC%20lecture.pdf 

The reason why the default setting is so strict in Trim Galore is mainly that in bisulfite sequencing it is very important that we do not include any artificial sequences in the read, because each base may end in inferring the underlying methylation state of a read. For other applications such as RNA-seq, ChIP-seq etc, where the mapping process allows more mismatches and where you are merely interested in the mapping position (rather than the highest possible accuracy for each base within a read), you could relax the stringency to e.g. `--stringency 3` (which is the default in Cutadapt, and probably also in Trimmomatic). This would mean that you would want at least 3 bases matching the adapter sequence (i.e. `AGA`) before it would get removed. I am sure that the blip of low `A` at the very last position would disappear this way.

Finally, I should probably also stress that while this phenomenon looks rather drastic in the base composition plot and most likely will cause the FastQC module to 'fail', it is perfectly expected, and will most likely not have any influence on the result of the mapping subsequently (for reads of 150 or 250bp trimming off a singular `A` from the end is unlikely to negatively affect the mapping rate noticably).

Regarding the K-mer plot: This plot shows that there is a slightly increased rate of sequences starting with `ATC`, however I am not sure that this is in any way significant. Since the k-mer plot tended to raise so many questions without hardly ever being useful, Simon disabled this plot to be shown since  a FastQC release over 2 years ago (maybe you should update FastQC for peace of mind).

Regarding both your questions together: I wouldn't worry about either of them, and just move on. Based on what you presented here there is no evidence that anything was wrong with your library. Do let me know if you have further questions.

**Comment by sjfleck** [comment]
Felix,
thank you so much. You have been very helpful
-Steve

**Comment by iranianuser** [comment]
Hi Felix,
I try to do trim galore for my WGBS data. The fastq files were good and just had a problem with base content which I think is normal in WGBS data. but I did trimming on fastq files because I had a bias in m-bias plot after alignment and methylation extraction. this is the m-bias plot:
![image](https://github.com/user-attachments/assets/3920ea4d-15f2-4a8b-9e56-5efe1d8e3ece)

what should I do? 
the command for trimming was:
`trim_galore --paired --clip_R1 5 --clip_R2 5 --stringency 3 *_1.fastq *_2.fastq`

thank you for your guidance

**Comment by iranianuser** [comment]
Sorry, it seems I forgot to include the main question in previous comment. I encountered a problem with K-mer content. There was no K-mer content initially, but after trimming, this section turned red and became problematic.
what should I do?

**Comment by FelixKrueger** [comment]
I would generally ignore the k-mer content in FastQC, in fact it has been taken out of default distribution some 5 years ago as it was mainly confusing people rather than helping. Especially in a bisulfite setting. Which type of sequencing is this? There are still some rather big biases in the data at the 5' end... maybe some additional trimming would be advisable...

**Comment by iranianuser** [comment]
Could the K-mers be due to strict trimming? Which additional trimming option would be better: using the `-q` 30 option or increasing `--clip_R` to 10? Or is there another option you would recommend? By the way, this is a library for whole-genome bisulfite sequencing:
**Library**:
Instrument: Illumina HiSeq 2000
Strategy: Bisulfite-Seq
Source: GENOMIC
Selection: RANDOM
Layout: PAIRED
Construction protocol: DNA was extracted with MasterPure kits Whole genome bisulfite sequencing libraries were generated using TruSeq DNA Sample preparation protocol (Illumina) with modifications. Bisulfate conversion was done after gel size selection using EZ DNA Methylation-Gold Kit (Zymo Research). To amplify bisulfate converted library Kapa Hifi Uracil+ (Kapa Biosystems) polymerase was used.

**Comment by FelixKrueger** [comment]
Again, I wouldn't recommend to interpret the k-mer plot for bisulfite sequencing, in all likelihood it will simply detect k-mers that have Cs in it which has a massive impact of the observed/expected ratio due to the generally low levels of C (which is the results of bisulfite conversion).

I would indeed be concerned about the methylation bias at the start. R1 starts off with higher methylation level in all contexts and is then quite variable for the first 6-8bp or so. In contrast, R2 starts with dramatically lower levels of methylation, that recovers slowly to similar levels to R1 (but not quite). Trimming off the first 8bp sounds like a quite and cautionary step.

**Comment by iranianuser** [comment]
I hope to get good results after trimming the first 8 bases with the `clip_r` option. Thank you for being with me throughout the process, and I am grateful for your precise guidance.
