### ISSUE TITLE
Why the “—paired” process reads in “single-end” mode?

### ISSUE THREAD

**Issue by HeXY0515** [FelixKrueger/TrimGalore#82]
Hi, 
it is interesting that when I apply "--paired" parameter for paired-end mode, but the log shows that  the  processing is in single-end mode.  The command line is :
“_trim_galore **--paired** --stringency 5 --quality 20 --fastqc --fastqc_args "--outdir trimgolare_rerun/fastqc" --trim-n --output_dir ./trimgolare_rerun --gzip --basename P18022438 --cores 8 --path_to_cutadapt /home/hexiaoyu/.local/bin/cutadapt P18022438LU01_combined_R1.fastq.gz P18022438LU01_combined_R2.fastq.gz_  “
part of the log is like this:
“_Command line parameters: -j 8 -e 0.1 -q 20 -O 5 --trim-n -a AGATCGGAAGAGC P18022438LU01_combined_R1.fastq.gz
Processing reads on 8 cores in **single-end** mode ...
Finished in 155.77 s (4 us/read; 14.46 M reads/minute)._”
but I run cutadapt separately ,the log shows:
"_Command line parameters: --cores 8 --output P18022440_cutadapt8cores_R1.fastq.gz --paired-output P18022440_cutadapt8cores_R2.fastq.gz -Z P18022440LU01_combined_R1.fastq.gz P18022440LU01_combined_R2.fastq.gz
Processing reads on 8 cores in **paired-end** mode .._."

Besides, TrimGalore runs faster than cutadapt. Does it the result of singe-end processing of cutadapt in TrimGalore?

**Comment by FelixKrueger** [comment]
Hi @HeXY0515 

Trim Galore does indeed run each of the reads in single-end mode individually, and then does a 'validation' run of both trimmed files where it does all sorts of things (e.g. length filtering, 3' or 5' clipping, N-trimming etc.) (this is also the reason why the files still have _val_ in their filenames in paired-end mode). This has mostly historical reasons because when we started using Trim Galore in for paired-end files back in ~2011/12 there simply wasn't a tool around that was handling paired-end data the way we wanted it...
