### ISSUE TITLE
problem running in paired mode persists

### ISSUE THREAD

**Issue by adamfreedman** [FelixKrueger/TrimGalore#93]
I've been using trimgalore for years now without issue, but just today downloaded the most recent version of trimgalore, and ran it with a current build of cutadapt via conda.  and yet, running in --paired mode, regardless of where I put the --paired flag (per a comment by matthewholding for a previously closed version of this issue), i get:

"Please provide an even number of input files for paired-end FastQ trimming! Aborting .."

**Comment by FelixKrueger** [comment]
That's odd, can you please link the exact command you were using?

**Comment by FelixKrueger** [comment]
I hope you have found the other files by now?

**Comment by adamfreedman** [comment]
sorry for not getting back to you sooner. i seem to recall finding a cmd line bug on my end that caused the issue.



Adam H. Freedman, PhD
Data Scientist
Faculty of Arts & Sciences Informatics Group
Harvard University
38 Oxford St
Cambridge, MA 02138
phone: +001 310 415 7145
________________________________

**Comment by FelixKrueger** [comment]
Excellent, I'm glad it got solved. Take care.

**Comment by SergioRLL** [comment]
Hello,
I've run into the same issue but I cannot find a clear solution. I've run the following, where C1 and C2 are directories in which I have the fastq.gz files.

`find fastq/C1 -name "*_R1.fastq.gz" | cut -d "_" -f1 | parallel -j 1 trim_galore --fastqc_args "-o ${C1}/fastqc_after_trim" -o ${C1}/trim_galore --paired {}\_R1.fastq.gz {}\_R2.fastq.gz`
`find fastq/C2 -name "*_R1_001.fastq.gz" | cut -d "_" -f1 | parallel -j 1 trim_galore --fastqc_args "-o ${C2}/fastqc_after_trim" -o ${C2}/trim_galore --paired {}\_R1_001.fastq.gz {}\_R2_001.fastq.gz`

Am I missing something here?

Thank you,
Sergio

**Comment by FelixKrueger** [comment]
Can you also post what is the output of these operations, and what happens next?

**Comment by SergioRLL** [comment]
At the end I used the command like this: `parallel trim_galore --paired --fastqc -o trim_galore/ {} {=s/_R1/_R2/=} ::: *_R1.fastq.gz`. 
I noticed it didn't work when I used `--fastqc_args` like in my previous post, is it possible that the argument has some issues?

The output I used to get was the following for every sample:

> Please provide an even number of input files for paired-end FastQ trimming! Aborting ...
> Multicore support not enabled. Proceeding with single-core trimming.
> Path to Cutadapt set as: 'cutadapt' (default)
> Cutadapt seems to be working fine (tested command 'cutadapt --version')
> Cutadapt version: 3.2
> single-core operation.
> No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)

**Comment by FelixKrueger** [comment]
OK, so Trim Galore is there and working, the same is true for Cutadapt, which means that the way you are trying to set this command with all the clever {}, substitutions is not doing what you want it to.

It appears that you are ending up with an uneven number of arguments, and this is not allowed in paired-end mode. What you want is that this part `{} {=s/_R1/_R2/=} ::: *_R1.fastq.gz` gets resolved to:

```
file_R1.fastq.gz file_R2.fastq.gz
```

Maybe you instead of using trim_galore outright you can substitute it with `echo`. I am sure one the command line expansion works, so will the trimming.

**Comment by SergioRLL** [comment]
OK, thank you for the feedback

**Comment by mtanic** [comment]
Hi Felix,

I am experiencing the same issue, command that used to work fine in not working with the latest trim_galore version 0.6.10.

 #!/bin/bash
  for f1 in ./*R1_001.fastq.gz
    do 
    f2=${f1%%R1_001.fastq.gz}'R2_001.fastq.gz' 
    echo $f1 $f2
    trim_galore  --trim-n 1 --fastqc -o ../trimmed --paired ${f1} ${f2} 
  done

this is the output that I gat for one sample in the folder:

EMQN2_S2_ME_L001_R1_001.fastq.gz EMQN2_S2_ME_L001_R2_001.fastq.gz
Multicore support not enabled. Proceeding with single-core trimming.
Path to Cutadapt set as: 'cutadapt' (default)
Cutadapt seems to be working fine (tested command 'cutadapt --version')
Cutadapt version: 3.5
single-core operation.
Proceeding with 'gzip' for decompression
To decrease CPU usage of decompression, please install 'igzip' and run again

No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)

Please provide an even number of input files for paired-end FastQ trimming! Aborting ...


Not sure what the issue is, do you have any hints?

Thank you in advance,
Miljana

**Comment by FelixKrueger** [comment]
My guess is the fact that you used `--trim-n 1`. This option does not take any arguments:

```
--trim-n                Removes Ns from either side of the read...
```

so the `1` would be interpreted as the first file, creating an odd number of files overall.

**Comment by mtanic** [comment]
Thank you for the super quick response! 
That solved it. It used to be --trim1 so I modified it erroneously.
